version: "3"
services:
  back:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - pelda_net

networks:
  pelda_net:
    driver: bridge
